// Code generated from Hermes CLI telegram_menu_commands; DO NOT EDIT.
package bot

import tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"

var HermesMenuCommands = []tgbotapi.BotCommand{
	{Command: "help", Description: "Show available commands (/help skills lists skill commands, /help <text> filters)"},
	{Command: "new", Description: "Start a new session (fresh session ID + history)"},
	{Command: "stop", Description: "Kill all running background processes"},
	{Command: "status", Description: "Show session, model, token, and context info"},
	{Command: "egress", Description: "Show Docker egress proxy status"},
	{Command: "resume", Description: "Resume a previously-named session"},
	{Command: "sessions", Description: "Browse and resume previous sessions"},
	{Command: "model", Description: "Switch model (session-scoped; --global to persist)"},
	{Command: "debug", Description: "Upload debug report (system info + logs) and get shareable links"},
	{Command: "restart", Description: "Gracefully restart the gateway after draining active runs"},
	{Command: "update", Description: "Update Hermes Agent to the latest version"},
	{Command: "commands", Description: "Browse all commands and skills (paginated)"},
	{Command: "approve", Description: "Approve a pending dangerous command"},
	{Command: "deny", Description: "Deny a pending dangerous command (optionally with a reason)"},
	{Command: "queue", Description: "Queue a prompt for the next turn, or list/edit/rm/move/clear queued prompts"},
	{Command: "steer", Description: "Inject a message after the next tool call without interrupting"},
	{Command: "bg", Description: "Run a prompt in a separate background session"},
	{Command: "btw", Description: "Ask a side question about the current conversation without interrupting it"},
	{Command: "reasoning", Description: "Manage reasoning effort and display"},
	{Command: "usage", Description: "Show token usage and rate limits; `reset` redeems a banked Codex limit reset"},
	{Command: "platform", Description: "Pause, resume, or list a failing gateway platform"},
	{Command: "profile", Description: "Show active profile name and home directory"},
	{Command: "whoami", Description: "Show your slash command access (admin / user)"},
	{Command: "start", Description: "Acknowledge platform start pings without a reply"},
	{Command: "topic", Description: "Enable or inspect Telegram DM topic sessions"},
	{Command: "save", Description: "Export the current conversation (bare /save shows usage)"},
	{Command: "retry", Description: "Retry the last message (resend to agent)"},
	{Command: "undo", Description: "Back up N user turns and re-prompt (default 1)"},
	{Command: "title", Description: "Set a title for the current session"},
	{Command: "branch", Description: "Branch the current session (explore a different path)"},
	{Command: "compress", Description: "Compress conversation context (add 'here [N]' to keep recent N turns; --preview shows what would happen)"},
	{Command: "rollback", Description: "List or restore filesystem checkpoints (restores keep your hand-edits; --all overrides)"},
	{Command: "pause", Description: "Pause new work globally (emergency stop); '/pause off' resumes"},
	{Command: "agents", Description: "Show active agents and running tasks"},
	{Command: "goal", Description: "Set a standing goal Hermes works on across turns until achieved"},
	{Command: "heartbeat", Description: "Set a recurring prompt that re-enters this session when idle"},
	{Command: "refine", Description: "Review this conversation now and save lessons to memory/skills"},
	{Command: "review", Description: "Spawn an independent subagent to review the work just discussed (PR, code, docs)"},
	{Command: "loop", Description: "Re-run a prompt on a recurring interval in this session"},
	{Command: "plan", Description: "Write a markdown implementation plan to .hermes/plans/ without executing anything"},
	{Command: "moa", Description: "Run one prompt through the default Mixture of Agents preset, then restore your model"},
	{Command: "subgoal", Description: "Add or manage extra criteria on the active goal"},
	{Command: "context", Description: "Show detailed context window view with usage gauge, category breakdown, compression stats, and throughput"},
	{Command: "sethome", Description: "Set this chat as the home channel"},
	{Command: "codex_runtime", Description: "Toggle codex app-server runtime for OpenAI/Codex models"},
	{Command: "personality", Description: "Set a predefined personality"},
	{Command: "diff", Description: "Show git changes in the working directory"},
	{Command: "footer", Description: "Toggle gateway runtime-metadata footer on final replies"},
	{Command: "yolo", Description: "Toggle YOLO mode (skip all dangerous command approvals)"},
	{Command: "approvals", Description: "Show or set the persistent dangerous-command approval mode"},
	{Command: "fast", Description: "Fast mode - OpenAI Priority Processing / Anthropic Fast Mode (normal/fast/auto/cold)"},
	{Command: "voice", Description: "Toggle voice mode"},
	{Command: "busy", Description: "Control how messages behave while Hermes is working"},
	{Command: "memory", Description: "Review pending memory writes / toggle the approval gate"},
	{Command: "bundles", Description: "List skill bundles (aliases /<name> for multiple skills)"},
	{Command: "learn", Description: "Learn a reusable skill from anything you describe (dirs, URLs, this chat, notes)"},
	{Command: "init", Description: "Generate or update AGENTS.md project instructions from a repo scan"},
	{Command: "suggestions", Description: "Review suggested automations (accept/dismiss)"},
	{Command: "blueprint", Description: "Set up an automation from a blueprint template"},
	{Command: "curator", Description: "Background skill maintenance (status, run, pin, archive, list-archived)"},
	{Command: "kanban", Description: "Multi-profile collaboration board (tasks, links, comments)"},
	{Command: "reload_mcp", Description: "Reload MCP servers from config"},
	{Command: "reload_skills", Description: "Re-scan ~/.hermes/skills/ for newly installed or removed skills"},
	{Command: "login", Description: "Sign in with a Nous account (keeps your connectors)"},
	{Command: "topup", Description: "Show your Nous balance and manage billing on the portal"},
	{Command: "insights", Description: "Show usage insights and analytics"},
	{Command: "version", Description: "Show Hermes Agent version"},
	{Command: "airtable", Description: "Airtable REST API via curl. Records C..."},
	{Command: "architecture_diagram", Description: "Dark-themed SVG architecture/cloud/in..."},
	{Command: "arxiv", Description: "Search arXiv papers by keyword, autho..."},
	{Command: "ascii_video", Description: "ASCII video: convert video/audio to c..."},
	{Command: "baoyu_infographic", Description: "Infographics: 21 layouts x 21 styles ..."},
	{Command: "blocked_page_recovery", Description: "Use when a fetch fails: 403/429, payw..."},
	{Command: "box", Description: "Box manages cloud files, sharing, sea..."},
	{Command: "claude_code", Description: "Delegate coding to Claude Code CLI (f..."},
	{Command: "claude_design", Description: "Design one-off HTML artifacts (landin..."},
	{Command: "codebase_inspection", Description: "Inspect codebases w/ pygount: LOC, la..."},
	{Command: "codex", Description: "Delegate coding to OpenAI Codex CLI (..."},
	{Command: "competitor_news_monitor", Description: "Watch named companies for material ne..."},
	{Command: "computer_use", Description: "Drive the desktop background-first; e..."},
	{Command: "design_md", Description: "Author/validate/export Google's DESIG..."},
	{Command: "document_to_action_items", Description: "Extract cited obligations, deadlines,..."},
	{Command: "docx", Description: "Create, read, edit, template, and rev..."},
	{Command: "dogfood", Description: "Exploratory QA of web apps: find bugs..."},
	{Command: "email_inbox_triage", Description: "Triage an inbox: prioritize threads, ..."},
	{Command: "gif_search", Description: "Search/download GIFs from Tenor via c..."},
	{Command: "github", Description: "GitHub via gh CLI: PRs, issues, revie..."},
	{Command: "google_workspace", Description: "Gmail, Calendar, Drive, Docs, Sheets ..."},
	{Command: "grounded_citations", Description: "Ground answers and documents in cited..."},
	{Command: "hermes_agent", Description: "Use, configure, theme, extend, and or..."},
	{Command: "hermes_agent_skill_authoring", Description: "Author in-repo SKILL.md files: frontm..."},
	{Command: "himalaya", Description: "Himalaya CLI: IMAP/SMTP email from te..."},
	{Command: "humanizer", Description: "Humanize text: strip AI-isms and add ..."},
	{Command: "inspecting_hermes_desktop_dom", Description: "Read the live Hermes desktop DOM/CSS ..."},
	{Command: "llm_wiki", Description: "Karpathy's LLM Wiki: build/query inte..."},
	{Command: "manim_video", Description: "Manim CE animations: 3Blue1Brown math..."},
	{Command: "maps", Description: "Geocode, POIs, routes, timezones via ..."},
	{Command: "meeting_action_items", Description: "Turn meeting notes into cited decisio..."},
	{Command: "node_inspect_debugger", Description: "Debug Node.js via --inspect + Chrome ..."},
	{Command: "notion", Description: "Notion API + ntn CLI: pages, database..."},
}
