package bot

import (
	"encoding/json"
	"fmt"
	"html"
	"log"
	"regexp"
	"strconv"
	"strings"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// SplitMessage splits a long message text into chunks of at most chunkSize runes,
// preferring to break at newlines or spaces.
func SplitMessage(text string, chunkSize int) []string {
	if len(text) <= chunkSize {
		return []string{text}
	}
	var chunks []string
	runes := []rune(text)
	for len(runes) > 0 {
		if len(runes) <= chunkSize {
			chunks = append(chunks, string(runes))
			break
		}
		cutPoint := chunkSize
		// Search backwards for a newline
		for i := chunkSize; i > chunkSize-300 && i > 0; i-- {
			if runes[i] == '\n' {
				cutPoint = i + 1
				break
			}
		}
		// If no newline, search for a space
		if cutPoint == chunkSize {
			for i := chunkSize; i > chunkSize-150 && i > 0; i-- {
				if runes[i] == ' ' {
					cutPoint = i + 1
					break
				}
			}
		}
		chunks = append(chunks, string(runes[:cutPoint]))
		runes = runes[cutPoint:]
	}
	return chunks
}

var (
	reFencedCode = regexp.MustCompile("(?s)```(\\w*)\n?(.*?)```")
	reInlineCode = regexp.MustCompile("`([^`\n]+)`")
	reHeader     = regexp.MustCompile(`(?m)^(#{1,6})\s+(.*)`)
	reBold       = regexp.MustCompile(`\*\*(.+?)\*\*`)
	reItalicUS   = regexp.MustCompile(`__(.+?)__`)
	reItalicAst  = regexp.MustCompile(`\*([^\*\n]+)\*`)
	reStrike     = regexp.MustCompile(`~~(.+?)~~`)
	reTableRow   = regexp.MustCompile(`^\s*\|(.+)\|\s*$`)
	reTableSep   = regexp.MustCompile(`^\s*\|?\s*(:?-+:?\s*\|)+\s*(:?-+:?)\s*\|?\s*$`)
)

// formatTablesForLegacyHTML converts markdown tables into clean monospace ASCII tables inside <pre> tags.
func formatTablesForLegacyHTML(text string) string {
	lines := strings.Split(text, "\n")
	var out []string
	var tableRows [][]string
	inTable := false

	flushTable := func() {
		if len(tableRows) == 0 {
			return
		}
		cols := len(tableRows[0])
		widths := make([]int, cols)
		for _, row := range tableRows {
			for i, cell := range row {
				if i < cols {
					runesLen := len([]rune(cell))
					if runesLen > widths[i] {
						widths[i] = runesLen
					}
				}
			}
		}

		out = append(out, "<pre>")
		for rowIdx, row := range tableRows {
			var lineParts []string
			for i := 0; i < cols; i++ {
				val := ""
				if i < len(row) {
					val = row[i]
				}
				pad := widths[i] - len([]rune(val))
				if pad < 0 {
					pad = 0
				}
				lineParts = append(lineParts, val+strings.Repeat(" ", pad))
			}
			out = append(out, strings.Join(lineParts, " | "))
			if rowIdx == 0 {
				var seps []string
				for _, w := range widths {
					seps = append(seps, strings.Repeat("-", w))
				}
				out = append(out, strings.Join(seps, "-+-"))
			}
		}
		out = append(out, "</pre>")
		tableRows = nil
	}

	for _, line := range lines {
		if m := reTableRow.FindStringSubmatch(line); m != nil {
			if reTableSep.MatchString(line) {
				continue
			}
			rawCells := strings.Split(m[1], "|")
			var cells []string
			for _, c := range rawCells {
				cells = append(cells, strings.TrimSpace(c))
			}
			tableRows = append(tableRows, cells)
			inTable = true
		} else {
			if inTable {
				flushTable()
				inTable = false
			}
			out = append(out, line)
		}
	}
	if inTable {
		flushTable()
	}
	return strings.Join(out, "\n")
}

// MarkdownToTelegramHTML converts standard Markdown (GFM) to Telegram-safe HTML for legacy clients.
func MarkdownToTelegramHTML(text string) string {
	// 1. Convert markdown tables to clean monospace ASCII tables first
	text = formatTablesForLegacyHTML(text)

	// 2. Extract and protect fenced code blocks
	var codeBlocks []string
	text = reFencedCode.ReplaceAllStringFunc(text, func(match string) string {
		parts := reFencedCode.FindStringSubmatch(match)
		lang := ""
		code := ""
		if len(parts) == 3 {
			lang = parts[1]
			code = parts[2]
		}
		tag := "<pre>"
		if lang != "" {
			tag = "<pre><code class=\"language-" + lang + "\">"
		}
		endTag := "</pre>"
		if lang != "" {
			endTag = "</code></pre>"
		}
		placeholder := "<<CB_" + string(rune('A'+len(codeBlocks))) + ">>"
		codeBlocks = append(codeBlocks, tag+html.EscapeString(strings.Trim(code, "\n"))+endTag)
		return placeholder
	})

	// Also protect any <pre> blocks generated by formatTablesForLegacyHTML
	rePre := regexp.MustCompile("(?s)<pre>.*?</pre>")
	var preBlocks []string
	text = rePre.ReplaceAllStringFunc(text, func(match string) string {
		placeholder := "<<PRE_" + string(rune('A'+len(preBlocks))) + ">>"
		preBlocks = append(preBlocks, match)
		return placeholder
	})

	// 3. Extract and protect inline codes
	var inlineCodes []string
	text = reInlineCode.ReplaceAllStringFunc(text, func(match string) string {
		parts := reInlineCode.FindStringSubmatch(match)
		code := parts[1]
		placeholder := "<<IC_" + string(rune('A'+len(inlineCodes))) + ">>"
		inlineCodes = append(inlineCodes, "<code>"+html.EscapeString(code)+"</code>")
		return placeholder
	})

	// 4. Escape remaining HTML entities
	text = html.EscapeString(text)

	// 5. Convert Headers (#, ##, ###) to <b>Header</b>\n
	text = reHeader.ReplaceAllString(text, "<b>$2</b>")

	// 6. Convert **bold** to <b>bold</b>
	text = reBold.ReplaceAllString(text, "<b>$1</b>")

	// 7. Convert __italic__ to <i>italic</i>
	text = reItalicUS.ReplaceAllString(text, "<i>$1</i>")

	// 8. Convert *italic* to <i>italic</i>
	text = reItalicAst.ReplaceAllString(text, "<i>$1</i>")

	// 9. Convert ~~strikethrough~~ to <s>strikethrough</s>
	text = reStrike.ReplaceAllString(text, "<s>$1</s>")

	// 10. Convert [text](url) to <a href="url">text</a>
	reLink := regexp.MustCompile(`\[([^\]]+)\]\(([^)]+)\)`)
	text = reLink.ReplaceAllString(text, `<a href="$2">$1</a>`)

	// 11. Restore protected blocks
	for i, cb := range codeBlocks {
		placeholder := "<<CB_" + string(rune('A'+i)) + ">>"
		text = strings.Replace(text, placeholder, cb, 1)
	}
	for i, pb := range preBlocks {
		placeholder := "<<PRE_" + string(rune('A'+i)) + ">>"
		text = strings.Replace(text, placeholder, pb, 1)
	}
	for i, ic := range inlineCodes {
		placeholder := "<<IC_" + string(rune('A'+i)) + ">>"
		text = strings.Replace(text, placeholder, ic, 1)
	}

	return text
}

// SendRichMessage sends a rich message using Telegram 12.9+ Bot API 10.x sendRichMessage.
// Supports native visual tables, headings, LaTeX math, blockquotes, checklists, up to 32,768 chars.
func SendRichMessage(bot *tgbotapi.BotAPI, chatID int64, markdown string, replyMarkup interface{}) (tgbotapi.Message, error) {
	richJSON, err := json.Marshal(map[string]interface{}{
		"markdown": markdown,
	})
	if err != nil {
		return tgbotapi.Message{}, err
	}

	params := tgbotapi.Params{
		"chat_id":      strconv.FormatInt(chatID, 10),
		"rich_message": string(richJSON),
	}
	if replyMarkup != nil {
		if rmJSON, err := json.Marshal(replyMarkup); err == nil {
			params["reply_markup"] = string(rmJSON)
		}
	}

	apiResp, err := bot.MakeRequest("sendRichMessage", params)
	if err != nil {
		return tgbotapi.Message{}, err
	}

	var msg tgbotapi.Message
	if err := json.Unmarshal(apiResp.Result, &msg); err != nil {
		return tgbotapi.Message{}, fmt.Errorf("failed to unmarshal sendRichMessage result: %w", err)
	}
	return msg, nil
}

// EditRichMessage edits an existing message using Telegram 12.9+ Bot API 10.x editMessageText with rich_message.
func EditRichMessage(bot *tgbotapi.BotAPI, chatID int64, messageID int, markdown string, replyMarkup interface{}) (tgbotapi.Message, error) {
	richJSON, err := json.Marshal(map[string]interface{}{
		"markdown": markdown,
	})
	if err != nil {
		return tgbotapi.Message{}, err
	}

	params := tgbotapi.Params{
		"chat_id":      strconv.FormatInt(chatID, 10),
		"message_id":   strconv.Itoa(messageID),
		"rich_message": string(richJSON),
	}
	if replyMarkup != nil {
		if rmJSON, err := json.Marshal(replyMarkup); err == nil {
			params["reply_markup"] = string(rmJSON)
		}
	}

	apiResp, err := bot.MakeRequest("editMessageText", params)
	if err != nil {
		return tgbotapi.Message{}, err
	}

	var msg tgbotapi.Message
	if err := json.Unmarshal(apiResp.Result, &msg); err != nil {
		return tgbotapi.Message{MessageID: messageID}, nil
	}
	return msg, nil
}

// SendSafeMessage attempts to send a message using modern Telegram 12.9+ Rich Message (native tables, headings).
// If rich message fails, it seamlessly falls back to legacy HTML, and finally plain text.
func SendSafeMessage(bot *tgbotapi.BotAPI, chatID int64, text string, replyMarkup interface{}) (tgbotapi.Message, error) {
	// 1. Try modern Telegram 12.9 Rich Message first
	msg, err := SendRichMessage(bot, chatID, text, replyMarkup)
	if err == nil {
		return msg, nil
	}

	log.Printf("[bot] SendRichMessage failed (%v), falling back to legacy HTML", err)

	// 2. Legacy fallback: split if text > 4000 runes
	chunks := SplitMessage(text, 4000)
	var lastSent tgbotapi.Message
	for i, chunk := range chunks {
		htmlText := MarkdownToTelegramHTML(chunk)
		m := tgbotapi.NewMessage(chatID, htmlText)
		m.ParseMode = tgbotapi.ModeHTML
		if i == len(chunks)-1 && replyMarkup != nil {
			m.ReplyMarkup = replyMarkup
		}
		sent, err := bot.Send(m)
		if err != nil {
			// Fallback to plain text
			m.Text = chunk
			m.ParseMode = ""
			sent, err = bot.Send(m)
			if err != nil {
				return lastSent, err
			}
		}
		lastSent = sent
	}
	return lastSent, nil
}

// EditSafeMessage attempts to edit a message using Rich Message first, falling back to legacy HTML or plain text.
func EditSafeMessage(bot *tgbotapi.BotAPI, chatID int64, messageID int, text string, replyMarkup *tgbotapi.InlineKeyboardMarkup) (tgbotapi.Message, error) {
	// 1. Try modern Telegram 12.9 Rich Message first
	msg, err := EditRichMessage(bot, chatID, messageID, text, replyMarkup)
	if err == nil {
		return msg, nil
	}
	if strings.Contains(err.Error(), "message is not modified") {
		return tgbotapi.Message{MessageID: messageID}, nil
	}

	log.Printf("[bot] EditRichMessage failed (%v), falling back to legacy HTML", err)

	legacyText := text
	if len([]rune(legacyText)) > 4000 {
		chunks := SplitMessage(legacyText, 4000)
		if len(chunks) > 0 {
			legacyText = chunks[0]
		}
	}

	htmlText := MarkdownToTelegramHTML(legacyText)
	edit := tgbotapi.NewEditMessageText(chatID, messageID, htmlText)
	edit.ParseMode = tgbotapi.ModeHTML
	if replyMarkup != nil {
		edit.ReplyMarkup = replyMarkup
	}

	sent, err := bot.Send(edit)
	if err != nil {
		if strings.Contains(err.Error(), "message is not modified") {
			return sent, nil
		}
		// Fallback to plain text
		edit.Text = legacyText
		edit.ParseMode = ""
		return bot.Send(edit)
	}
	return sent, nil
}
